package pe.com.soappet.dominio;
// Generated 21/05/2015 12:08:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private int idDoctor;
     private String nombre;
     private String apePaterno;
     private String apeMaterno;
     private String correo;
     private String celular;
     private String telefono;
     private String dni;
     private int estado;
    
    public Doctor() {
    }

	
    public Doctor(int idDoctor) {
        this.idDoctor = idDoctor;
    }
  
    public Doctor(int idDoctor, String nombre, String apePaterno, String apeMaterno, String correo, String celular, String telefono, String dni) {
        this.idDoctor = idDoctor;
        this.nombre = nombre;
        this.apePaterno = apePaterno;
        this.apeMaterno = apeMaterno;
        this.correo = correo;
        this.celular = celular;
        this.telefono = telefono;
        this.dni = dni;
    }
   
    public int getIdDoctor() {
        return this.idDoctor;
    }
    
    public void setIdDoctor(int idDoctor) {
        this.idDoctor = idDoctor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApePaterno() {
        return this.apePaterno;
    }
    
    public void setApePaterno(String apePaterno) {
        this.apePaterno = apePaterno;
    }
    public String getApeMaterno() {
        return this.apeMaterno;
    }
    
    public void setApeMaterno(String apeMaterno) {
        this.apeMaterno = apeMaterno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    

    /**
     * @return the estado
     */
    public int getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


