package pe.com.soappet.dominio;
// Generated 21/05/2015 12:08:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HorarioDoctor generated by hbm2java
 */
public class HorarioDoctor  implements java.io.Serializable {


     private int id;
     private Doctor doctor;
     private Date fechaEntrada;
     private Date fechaSalida;

    public HorarioDoctor() {
    }

	
    public HorarioDoctor(int id) {
        this.id = id;
    }
    public HorarioDoctor(int id, Doctor doctor, Date fechaEntrada, Date fechaSalida) {
       this.id = id;
       this.doctor = doctor;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


